# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Grade three\DataBase\lab2\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 453)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 210, 72, 15))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 220, 72, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 144, 72, 41))
        self.label_3.setObjectName("label_3")
        self.user = QtWidgets.QLineEdit(self.centralwidget)
        self.user.setGeometry(QtCore.QRect(240, 150, 113, 31))
        self.user.setObjectName("user")
        self.key = QtWidgets.QLineEdit(self.centralwidget)
        self.key.setGeometry(QtCore.QRect(240, 220, 113, 31))
        self.key.setEchoMode(QtWidgets.QLineEdit.Password)
        self.key.setObjectName("key")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(170, 300, 93, 28))
        self.login.setObjectName("login")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(310, 300, 93, 28))
        self.logout.setObjectName("logout")
        self.stu = QtWidgets.QRadioButton(self.centralwidget)
        self.stu.setGeometry(QtCore.QRect(120, 270, 71, 19))
        self.stu.setObjectName("stu")
        self.teach = QtWidgets.QRadioButton(self.centralwidget)
        self.teach.setGeometry(QtCore.QRect(210, 270, 71, 19))
        self.teach.setObjectName("teach")
        self.admin = QtWidgets.QRadioButton(self.centralwidget)
        self.admin.setGeometry(QtCore.QRect(310, 270, 71, 19))
        self.admin.setObjectName("admin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "  密码"))
        self.label_3.setText(_translate("MainWindow", " 用户名"))
        self.login.setText(_translate("MainWindow", "登录"))
        self.logout.setText(_translate("MainWindow", "取消"))
        self.stu.setText(_translate("MainWindow", "学生"))
        self.teach.setText(_translate("MainWindow", "老师"))
        self.admin.setText(_translate("MainWindow", "管理员"))
        self.menu.setTitle(_translate("MainWindow", "登录"))
