# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Grade three\DataBase\lab2\ui\teachmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.change = QtWidgets.QPushButton(self.centralwidget)
        self.change.setGeometry(QtCore.QRect(430, 100, 151, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.change.setFont(font)
        self.change.setObjectName("change")
        self.info = QtWidgets.QPushButton(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(130, 100, 161, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.grade = QtWidgets.QPushButton(self.centralwidget)
        self.grade.setGeometry(QtCore.QRect(440, 270, 151, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.grade.setFont(font)
        self.grade.setObjectName("grade")
        self.course = QtWidgets.QPushButton(self.centralwidget)
        self.course.setGeometry(QtCore.QRect(130, 270, 161, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.course.setFont(font)
        self.course.setObjectName("course")
        self.key = QtWidgets.QRadioButton(self.centralwidget)
        self.key.setGeometry(QtCore.QRect(610, 170, 115, 19))
        self.key.setObjectName("key")
        self.image = QtWidgets.QRadioButton(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(610, 120, 115, 19))
        self.image.setObjectName("image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.change.setText(_translate("MainWindow", "修改信息"))
        self.info.setText(_translate("MainWindow", "基本信息"))
        self.grade.setText(_translate("MainWindow", "成绩赋予"))
        self.course.setText(_translate("MainWindow", "开课"))
        self.key.setText(_translate("MainWindow", "密码"))
        self.image.setText(_translate("MainWindow", "头像"))
